// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOD4ZpmEM1ATI7O7rUcc7rXMI6sLz1P1M',
    appId: '1:1043398719163:web:7537e5f004d14f4fdd5b9e',
    messagingSenderId: '1043398719163',
    projectId: 'chatnew-4e7cc',
    authDomain: 'chatnew-4e7cc.firebaseapp.com',
    storageBucket: 'chatnew-4e7cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0TvKwLQ8TjT1tTNX9s-qBmncUDdRq-f0',
    appId: '1:1043398719163:android:fc2d98ad5ce3277add5b9e',
    messagingSenderId: '1043398719163',
    projectId: 'chatnew-4e7cc',
    storageBucket: 'chatnew-4e7cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnaTowSEbXhynEW9iZSqWjl5Wv9Ut6Mds',
    appId: '1:1043398719163:ios:769af6af327651a1dd5b9e',
    messagingSenderId: '1043398719163',
    projectId: 'chatnew-4e7cc',
    storageBucket: 'chatnew-4e7cc.appspot.com',
    iosBundleId: 'com.example.chattApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnaTowSEbXhynEW9iZSqWjl5Wv9Ut6Mds',
    appId: '1:1043398719163:ios:769af6af327651a1dd5b9e',
    messagingSenderId: '1043398719163',
    projectId: 'chatnew-4e7cc',
    storageBucket: 'chatnew-4e7cc.appspot.com',
    iosBundleId: 'com.example.chattApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOD4ZpmEM1ATI7O7rUcc7rXMI6sLz1P1M',
    appId: '1:1043398719163:web:5f772d43c1208047dd5b9e',
    messagingSenderId: '1043398719163',
    projectId: 'chatnew-4e7cc',
    authDomain: 'chatnew-4e7cc.firebaseapp.com',
    storageBucket: 'chatnew-4e7cc.appspot.com',
  );

}